name = "crc-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "https://www.challengerun.net,https://challengerun.net"
SUPABASE_URL = "https://riwcekvwpwmbtihjqhmh.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpd2Nla3Z3cHdtYnRpaGpxaG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MzU0MTksImV4cCI6MjA4NTIxMTQxOX0.eSO-2YiD_bbSMhU72LiyI0OnRqOOtapA2A2hUqaXYOM"
